_OPCODE(op_func, NULL,         0,   OP_LOAD)
_OPCODE(op_func, NULL,         0,   OP_REPL_READ)
_OPCODE(op_func, NULL,         0,   OP_REPL_EVAL)
_OPCODE(op_func, NULL,         0,   OP_REPL_PRINT)
_OPCODE(op_func, NULL,         0,   OP_REPL_LOOP)
_OPCODE(op_func, "define",     SYNTAX,  OP_DEFINE)
_OPCODE(op_func, "lambda",     SYNTAX,  OP_LAMBDA)
_OPCODE(op_func, "display",    PROC,    OP_DISPLAY)
